spring:
  application:
    name: gateway-server
  cloud:
    config:
      uri: http://localhost:8080


server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurakserver:8080/eureka